INSERT INTO template_staging (
    "template_name",
    "application",
    "creator",
    "frozen",
    "OWNER/PATH",
    "TABLE/FILE",
    "table_row_count",
    "action",
    "scramble_scheme",
    "COLUMN/PAGE",
    "datatype",
    "data_classification",
    "anonymization_method",
    "addl_info1",
    "addl_info2",
    "addl_info3",
    "addl_info4",
    "method_code",
    "length",
    "table_file_parameter",
    "subset_enabled",
    "subset_condition",
    "conditional_masking_enabled",
    "masking_condition"
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
